In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from  sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder
import pickle

In [5]:
data= pd.read_csv("car_price_dataset.csv")

In [6]:
data.shape

(10000, 10)

In [7]:
data.head()

Brand   Model  Year  Engine_Size Fuel_Type    Transmission  Mileage  \
0         Kia     Rio  2020          4.2    Diesel          Manual   289944   
1   Chevrolet  Malibu  2012          2.0    Hybrid       Automatic     5356   
2    Mercedes     GLA  2020          4.2    Diesel       Automatic   231440   
3        Audi      Q5  2023          2.0  Electric          Manual   160971   
4  Volkswagen    Golf  2003          2.6    Hybrid  Semi-Automatic   286618   

   Doors  Owner_Count  Price  
0      3            5   8501  
1      2            3  12092  
2      4            2  11171  
3      2            1  11780  
4      3            3   2867

In [18]:
unique_brands = data["Brand"].unique()  # Get unique brands
print(unique_brands)
unique_models = data["Model"].unique()  # Get unique brands
print(unique_models)
unique_year = data["Year"].unique()  # Get unique brands
print(unique_year)
unique_doors = data["Doors"].unique()  # Get unique brands
print(unique_doors)
unique_owners = data["Owner_Count"].unique()  # Get unique brands
print(unique_owners)




['Kia' 'Chevrolet' 'Mercedes' 'Audi' 'Volkswagen' 'Toyota' 'Honda' 'BMW'
 'Hyundai' 'Ford']
['Rio' 'Malibu' 'GLA' 'Q5' 'Golf' 'Camry' 'Civic' 'Sportage' 'RAV4'
 '5 Series' 'CR-V' 'Elantra' 'Tiguan' 'Equinox' 'Explorer' 'A3' '3 Series'
 'Tucson' 'Passat' 'Impala' 'Corolla' 'Optima' 'Fiesta' 'A4' 'Focus'
 'E-Class' 'Sonata' 'C-Class' 'X5' 'Accord']
[2020 2012 2023 2003 2007 2010 2001 2014 2005 2013 2009 2004 2017 2006
 2000 2021 2018 2016 2011 2022 2008 2015 2002 2019]
[3 2 4 5]
[5 3 2 1 4]


In [19]:
brand_counts_sorted = data["Brand"].value_counts().sort_index()
print(brand_counts_sorted)


Brand
Audi          1038
BMW            999
Chevrolet     1003
Ford          1048
Honda         1009
Hyundai        995
Kia            976
Mercedes       942
Toyota         970
Volkswagen    1020
Name: count, dtype: int64


In [21]:
data["Brand_ID"], unique_models = pd.factorize(data["Brand"])
print(data[["Brand", "Brand_ID"]])


           Brand  Brand_ID
0            Kia         0
1      Chevrolet         1
2       Mercedes         2
3           Audi         3
4     Volkswagen         4
...          ...       ...
9995         Kia         0
9996   Chevrolet         1
9997         BMW         7
9998        Ford         9
9999  Volkswagen         4

[10000 rows x 2 columns]


In [8]:
data.isnull().sum()

Brand           0
Model           0
Year            0
Engine_Size     0
Fuel_Type       0
Transmission    0
Mileage         0
Doors           0
Owner_Count     0
Price           0
dtype: int64

In [19]:
labelEncoder = LabelEncoder()
data["Brand"] = labelEncoder.fit_transform(data["Brand"])
data["Model"] = labelEncoder.fit_transform(data["Model"])
data["Fuel_Type"] = labelEncoder.fit_transform(data["Fuel_Type"])
data["Transmission"] =labelEncoder.fit_transform(data["Transmission"])


In [20]:
data.head()

Brand  Model  Year  Engine_Size  Fuel_Type  Transmission  Mileage  Doors  \
0      6     24  2020          4.2          0             1   289944      3   
1      2     19  2012          2.0          2             0     5356      2   
2      7     16  2020          4.2          0             0   231440      4   
3      0     22  2023          2.0          1             1   160971      2   
4      9     17  2003          2.6          2             2   286618      3   

   Owner_Count  Price  
0            5   8501  
1            3  12092  
2            2  11171  
3            1  11780  
4            3   2867

In [25]:
X= np.array(data.drop(columns = ["Price"]))
y= np.array(data["Price"])

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [28]:
model =LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [30]:
score = model.score(X_test, y_test)
print(f"score: (score)")

score: (score)


In [31]:
model.predict([[6,24,2020,4.2,0,1,289944,3,5]])	

array([9920.78621885])

In [32]:
model.coef_

array([-3.44314972e-01,  1.74085763e+00,  2.97946076e+02,  9.91167457e+02,
       -9.82134444e+01, -7.72802748e+02, -1.98805686e-02, -1.78333365e+00,
        1.50477102e+00])

In [34]:
pd.DataFrame(model.coef_,["Brand", "Model", "Year", "Engine_Size", "Fuel_Type", "Transmission","Mileage" , "Doors","Owner_Count"],columns=["coef"])

coef
Brand          -0.344315
Model           1.740858
Year          297.946076
Engine_Size   991.167457
Fuel_Type     -98.213444
Transmission -772.802748
Mileage        -0.019881
Doors          -1.783334
Owner_Count     1.504771

In [ ]:
#save model
with open(